name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: InstallFyne
      run: go get fyne.io/fyne/v2/cmd/fyne

    - name: Package
      run: fyne package -os linux -release -icon logo.icon
